dependencies:
  - name: container-linux-update-operator
    repository: https://charts.eu-de-2.cloud.sap
    version: v0.0.1

  - name: conntrack-nanny
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.0
    condition: conntrack-nanny.enabled

  - name: dex
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.8.0

  - name: kubernetes-dashboard
    repository: https://charts.eu-de-2.cloud.sap
    version: 1.6.1

  - name: nginx-ingress
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 1.20.0

  - name: node-problem-detector
    repository: https://charts.eu-de-2.cloud.sap
    version: 1.2.1

  - name: vice-president
    repository: https://charts.eu-de-2.cloud.sap
    version: 1.0.5

  - name: sysctl
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.0.1

  - name: disco
    repository: https://charts.eu-de-2.cloud.sap
    version: 1.1.2
    condition: disco.enabled

  - name: kube-proxy 
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.4.0
    condition: kube-proxy.enabled